
package net.codejava.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Product", targetNamespace = "http://codejava.net/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Product {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getName", targetNamespace = "http://codejava.net/", className = "net.codejava.test.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://codejava.net/", className = "net.codejava.test.GetNameResponse")
    @Action(input = "http://codejava.net/Product/getNameRequest", output = "http://codejava.net/Product/getNameResponse")
    public String getName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPrice", targetNamespace = "http://codejava.net/", className = "net.codejava.test.GetPrice")
    @ResponseWrapper(localName = "getPriceResponse", targetNamespace = "http://codejava.net/", className = "net.codejava.test.GetPriceResponse")
    @Action(input = "http://codejava.net/Product/getPriceRequest", output = "http://codejava.net/Product/getPriceResponse")
    public int getPrice();

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "sell", targetNamespace = "http://codejava.net/", className = "net.codejava.test.Sell")
    @ResponseWrapper(localName = "sellResponse", targetNamespace = "http://codejava.net/", className = "net.codejava.test.SellResponse")
    @Action(input = "http://codejava.net/Product/sellRequest", output = "http://codejava.net/Product/sellResponse")
    public void sell(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
